//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vocup.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vocup.Properties.language", typeof(language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vokabelhefte hinzufügen.
        /// </summary>
        internal static string add_title {
            get {
                return ResourceManager.GetString("add_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to und.
        /// </summary>
        internal static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocup Backup-Datei.
        /// </summary>
        internal static string backup {
            get {
                return ResourceManager.GetString("backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Importieren der Datei ist ein Fehler aufgetreten..
        /// </summary>
        internal static string can_not_import {
            get {
                return ResourceManager.GetString("can_not_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        internal static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanisch.
        /// </summary>
        internal static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportieren.
        /// </summary>
        internal static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertig.
        /// </summary>
        internal static string fertig {
            get {
                return ResourceManager.GetString("fertig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beenden.
        /// </summary>
        internal static string finish {
            get {
                return ResourceManager.GetString("finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fremdsprache.
        /// </summary>
        internal static string foreign_language {
            get {
                return ResourceManager.GetString("foreign_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Französisch.
        /// </summary>
        internal static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern Sie bitte das Vokabelheft vor dem Drucken ab..
        /// </summary>
        internal static string have_to_save {
            get {
                return ResourceManager.GetString("have_to_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern Sie bitte das Vokabelheft vor dem Versenden ab..
        /// </summary>
        internal static string have_to_save_mail {
            get {
                return ResourceManager.GetString("have_to_save_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importieren.
        /// </summary>
        internal static string import {
            get {
                return ResourceManager.GetString("import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italienisch.
        /// </summary>
        internal static string it {
            get {
                return ResourceManager.GetString("it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuletzt geübt am.
        /// </summary>
        internal static string last_practise {
            get {
                return ResourceManager.GetString("last_practise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Zusammenführen der Vokabelhefte ist ein Fehler aufgetreten..
        /// </summary>
        internal static string merge_error {
            get {
                return ResourceManager.GetString("merge_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Vokabelheft konnte nicht zusammengeführt werden..
        /// </summary>
        internal static string merge_error_1 {
            get {
                return ResourceManager.GetString("merge_error_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vokabelhefte konnten nicht zusammengeführt werden..
        /// </summary>
        internal static string merge_error_over_1 {
            get {
                return ResourceManager.GetString("merge_error_over_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Vokabelhefte wurden erfolgreich zusammengeführt..
        /// </summary>
        internal static string merge_success {
            get {
                return ResourceManager.GetString("merge_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Vokabelheft konnte nicht zusammengeführt werden, weil dazu eine neuere Version von Vocup benötigt wird. Möchten Sie nach Updates suchen?.
        /// </summary>
        internal static string merge_to_new_1 {
            get {
                return ResourceManager.GetString("merge_to_new_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vokabelhefte konnten nicht zusammengeführt werden, weil dazu eine neuere Version von Vocup benötigt wird. Möchten Sie nach Updates suchen?.
        /// </summary>
        internal static string merge_to_new_over {
            get {
                return ResourceManager.GetString("merge_to_new_over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie Ihre Übungsergebnisse und/oder  Änderungen im Vokabelheft speichern?.
        /// </summary>
        internal static string messagebox_ask_to_save {
            get {
                return ResourceManager.GetString("messagebox_ask_to_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim erstellen der Datensicherung ist ein Fehler aufgetreten!.
        /// </summary>
        internal static string messagebox_backup_error {
            get {
                return ResourceManager.GetString("messagebox_backup_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folgende Sonderzeichentabellen konnten nicht gesichert werden:.
        /// </summary>
        internal static string messagebox_backup_error_chars {
            get {
                return ResourceManager.GetString("messagebox_backup_error_chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folgende Vokabelhefte konnten nicht gesichert werden:.
        /// </summary>
        internal static string messagebox_backup_error_vhf {
            get {
                return ResourceManager.GetString("messagebox_backup_error_vhf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ergebnis-Datei(en) konnte(n) nicht gesichert werden!.
        /// </summary>
        internal static string messagebox_backup_error_vhr {
            get {
                return ResourceManager.GetString("messagebox_backup_error_vhr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Wiederherstellen der Datensicherung ist ein Fehler aufgetreten!.
        /// </summary>
        internal static string messagebox_backup_restore_error {
            get {
                return ResourceManager.GetString("messagebox_backup_restore_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folgende Sonderzeichentabellen konnten nicht wiederhergestellt werden:.
        /// </summary>
        internal static string messagebox_backup_restore_error_chars {
            get {
                return ResourceManager.GetString("messagebox_backup_restore_error_chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folgende Vokabelhefte konnten nicht wiederhergestellt werden:.
        /// </summary>
        internal static string messagebox_backup_restore_error_vhf {
            get {
                return ResourceManager.GetString("messagebox_backup_restore_error_vhf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ergebnis-Datei(en) konnte(n) nicht wiederhergestellt werden!.
        /// </summary>
        internal static string messagebox_backup_restore_error_vhr {
            get {
                return ResourceManager.GetString("messagebox_backup_restore_error_vhr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datensicherung wurde erfolgreich wiederhergestellt..
        /// </summary>
        internal static string messagebox_backup_restore_success {
            get {
                return ResourceManager.GetString("messagebox_backup_restore_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datensicherung wurde erfolgreich erstellt..
        /// </summary>
        internal static string messagebox_backup_success {
            get {
                return ResourceManager.GetString("messagebox_backup_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Vokabel konnte nicht geändert werden, da sie bereits vorhanden ist!.
        /// </summary>
        internal static string messagebox_cant_edit {
            get {
                return ResourceManager.GetString("messagebox_cant_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei ist fehlerhaft!.
        /// </summary>
        internal static string messagebox_faulty_file {
            get {
                return ResourceManager.GetString("messagebox_faulty_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Laden der Ergebnisse!.
        /// </summary>
        internal static string messagebox_fautly_results {
            get {
                return ResourceManager.GetString("messagebox_fautly_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei diesem Vokabelheft handelt es sich um eine Kopie, dessenn Inhalt mit der Orginaldatei nicht identisch ist. Die Ergebnisse der Übungen werden bei dieser Datei gelöscht..
        /// </summary>
        internal static string messagebox_file_copy {
            get {
                return ResourceManager.GetString("messagebox_file_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei benötigt eine neuere Version von Vocup. Möchten Sie nach Updates suchen?.
        /// </summary>
        internal static string messagebox_new_program_version {
            get {
                return ResourceManager.GetString("messagebox_new_program_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei dieser Datei handelt es sich nicht um ein Vokabelheft!.
        /// </summary>
        internal static string messagebox_no_vhf {
            get {
                return ResourceManager.GetString("messagebox_no_vhf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Öffnen der Datei!.
        /// </summary>
        internal static string messagebox_reading_fault {
            get {
                return ResourceManager.GetString("messagebox_reading_fault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Vokabel ist bereits vorhanden!.
        /// </summary>
        internal static string messagebox_vocable_exists {
            get {
                return ResourceManager.GetString("messagebox_vocable_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocup.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herzlichen Glückwunsch! Sie haben bereits alle Vokabeln mehrmals hintereinander richtig übersetzt.
        ///	
        ///Tipp: Unter Optionen können Sie festlegen, wie oft eine Vokabel richtig hintereinander übersetzt werden muss, 
        ///damit sie als gelernt eingestuft wird.
        ///.
        /// </summary>
        internal static string no_vocables_to_learn {
            get {
                return ResourceManager.GetString("no_vocables_to_learn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vokabelheft öffnen.
        /// </summary>
        internal static string open_title {
            get {
                return ResourceManager.GetString("open_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muttersprache.
        /// </summary>
        internal static string own_language {
            get {
                return ResourceManager.GetString("own_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vokabelhefte.
        /// </summary>
        internal static string personal_directory {
            get {
                return ResourceManager.GetString("personal_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falsch! (richtig wäre: .
        /// </summary>
        internal static string practise_false {
            get {
                return ResourceManager.GetString("practise_false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teilweise korrekt! (Richtig wäre: .
        /// </summary>
        internal static string practise_nearly_right {
            get {
                return ResourceManager.GetString("practise_nearly_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korrekt!.
        /// </summary>
        internal static string practise_right {
            get {
                return ResourceManager.GetString("practise_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datensicherung öffnen.
        /// </summary>
        internal static string restore_backup {
            get {
                return ResourceManager.GetString("restore_backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rumänisch.
        /// </summary>
        internal static string ro {
            get {
                return ResourceManager.GetString("ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie das Vokabelheft speichern bevor sie fortfahren? Alle nicht gespeicherten Daten gehen verloren..
        /// </summary>
        internal static string save_before_update {
            get {
                return ResourceManager.GetString("save_before_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vokabelheft speichern.
        /// </summary>
        internal static string save_title {
            get {
                return ResourceManager.GetString("save_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datensicherung speichern.
        /// </summary>
        internal static string save_title_backup {
            get {
                return ResourceManager.GetString("save_title_backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seite.
        /// </summary>
        internal static string site {
            get {
                return ResourceManager.GetString("site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synonym.
        /// </summary>
        internal static string synonym {
            get {
                return ResourceManager.GetString("synonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übersetzen Sie von.
        /// </summary>
        internal static string translate_from {
            get {
                return ResourceManager.GetString("translate_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nach.
        /// </summary>
        internal static string translate_to {
            get {
                return ResourceManager.GetString("translate_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geübt.
        /// </summary>
        internal static string translated {
            get {
                return ResourceManager.GetString("translated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das gewählte Vokabelheft existiert nicht mehr..
        /// </summary>
        internal static string treeview_doesnt_exists {
            get {
                return ResourceManager.GetString("treeview_doesnt_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vokabeln.
        /// </summary>
        internal static string vocable {
            get {
                return ResourceManager.GetString("vocable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vokabel bearbeiten.
        /// </summary>
        internal static string vocable_edit_title {
            get {
                return ResourceManager.GetString("vocable_edit_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vokabelheft bearbeiten.
        /// </summary>
        internal static string vocable_file_edit_title {
            get {
                return ResourceManager.GetString("vocable_file_edit_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vokabelheft.
        /// </summary>
        internal static string vocable_file_name {
            get {
                return ResourceManager.GetString("vocable_file_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamthaft.
        /// </summary>
        internal static string vocables_in_all {
            get {
                return ResourceManager.GetString("vocables_in_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falsche Eingabe.
        /// </summary>
        internal static string wrong_text {
            get {
                return ResourceManager.GetString("wrong_text", resourceCulture);
            }
        }
    }
}
