//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vocup.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vocup.Properties.language", typeof(language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern Sie bitte das Vokabelheft vor dem Drucken ab..
        /// </summary>
        internal static string have_to_save {
            get {
                return ResourceManager.GetString("have_to_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim erstellen der Datensicherung ist ein Fehler aufgetreten!.
        /// </summary>
        internal static string messagebox_backup_error {
            get {
                return ResourceManager.GetString("messagebox_backup_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folgende Sonderzeichentabellen konnten nicht gesichert werden:.
        /// </summary>
        internal static string messagebox_backup_error_chars {
            get {
                return ResourceManager.GetString("messagebox_backup_error_chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folgende Vokabelhefte konnten nicht gesichert werden:.
        /// </summary>
        internal static string messagebox_backup_error_vhf {
            get {
                return ResourceManager.GetString("messagebox_backup_error_vhf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ergebnis-Datei(en) konnte(n) nicht gesichert werden!.
        /// </summary>
        internal static string messagebox_backup_error_vhr {
            get {
                return ResourceManager.GetString("messagebox_backup_error_vhr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Wiederherstellen der Datensicherung ist ein Fehler aufgetreten!.
        /// </summary>
        internal static string messagebox_backup_restore_error {
            get {
                return ResourceManager.GetString("messagebox_backup_restore_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folgende Sonderzeichentabellen konnten nicht wiederhergestellt werden:.
        /// </summary>
        internal static string messagebox_backup_restore_error_chars {
            get {
                return ResourceManager.GetString("messagebox_backup_restore_error_chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folgende Vokabelhefte konnten nicht wiederhergestellt werden:.
        /// </summary>
        internal static string messagebox_backup_restore_error_vhf {
            get {
                return ResourceManager.GetString("messagebox_backup_restore_error_vhf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ergebnis-Datei(en) konnte(n) nicht wiederhergestellt werden!.
        /// </summary>
        internal static string messagebox_backup_restore_error_vhr {
            get {
                return ResourceManager.GetString("messagebox_backup_restore_error_vhr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datensicherung wurde erfolgreich wiederhergestellt..
        /// </summary>
        internal static string messagebox_backup_restore_success {
            get {
                return ResourceManager.GetString("messagebox_backup_restore_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datensicherung wurde erfolgreich erstellt..
        /// </summary>
        internal static string messagebox_backup_success {
            get {
                return ResourceManager.GetString("messagebox_backup_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei dieser Datei handelt es sich nicht um ein Vokabelheft!.
        /// </summary>
        internal static string messagebox_no_vhf {
            get {
                return ResourceManager.GetString("messagebox_no_vhf", resourceCulture);
            }
        }
    }
}
