//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vocup.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vocup.Properties.language", typeof(language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Importieren der Datei ist ein Fehler aufgetreten..
        /// </summary>
        internal static string can_not_import {
            get {
                return ResourceManager.GetString("can_not_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern Sie bitte das Vokabelheft vor dem Drucken ab..
        /// </summary>
        internal static string have_to_save {
            get {
                return ResourceManager.GetString("have_to_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern Sie bitte das Vokabelheft vor dem Versenden ab..
        /// </summary>
        internal static string have_to_save_mail {
            get {
                return ResourceManager.GetString("have_to_save_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Zusammenführen der Vokabelhefte ist ein Fehler aufgetreten..
        /// </summary>
        internal static string merge_error {
            get {
                return ResourceManager.GetString("merge_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Vokabelheft konnte nicht zusammengeführt werden..
        /// </summary>
        internal static string merge_error_1 {
            get {
                return ResourceManager.GetString("merge_error_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vokabelhefte konnten nicht zusammengeführt werden..
        /// </summary>
        internal static string merge_error_over_1 {
            get {
                return ResourceManager.GetString("merge_error_over_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Vokabelhefte wurden erfolgreich zusammengeführt..
        /// </summary>
        internal static string merge_success {
            get {
                return ResourceManager.GetString("merge_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Vokabelheft konnte nicht zusammengeführt werden, weil dazu eine neuere Version von Vocup benötigt wird. Möchten Sie nach Updates suchen?.
        /// </summary>
        internal static string merge_to_new_1 {
            get {
                return ResourceManager.GetString("merge_to_new_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vokabelhefte konnten nicht zusammengeführt werden, weil dazu eine neuere Version von Vocup benötigt wird. Möchten Sie nach Updates suchen?.
        /// </summary>
        internal static string merge_to_new_over {
            get {
                return ResourceManager.GetString("merge_to_new_over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie Ihre Übungsergebnisse und/oder  Änderungen im Vokabelheft speichern?.
        /// </summary>
        internal static string messagebox_ask_to_save {
            get {
                return ResourceManager.GetString("messagebox_ask_to_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim erstellen der Datensicherung ist ein Fehler aufgetreten!.
        /// </summary>
        internal static string messagebox_backup_error {
            get {
                return ResourceManager.GetString("messagebox_backup_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folgende Sonderzeichentabellen konnten nicht gesichert werden:.
        /// </summary>
        internal static string messagebox_backup_error_chars {
            get {
                return ResourceManager.GetString("messagebox_backup_error_chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folgende Vokabelhefte konnten nicht gesichert werden:.
        /// </summary>
        internal static string messagebox_backup_error_vhf {
            get {
                return ResourceManager.GetString("messagebox_backup_error_vhf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ergebnis-Datei(en) konnte(n) nicht gesichert werden!.
        /// </summary>
        internal static string messagebox_backup_error_vhr {
            get {
                return ResourceManager.GetString("messagebox_backup_error_vhr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Wiederherstellen der Datensicherung ist ein Fehler aufgetreten!.
        /// </summary>
        internal static string messagebox_backup_restore_error {
            get {
                return ResourceManager.GetString("messagebox_backup_restore_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folgende Sonderzeichentabellen konnten nicht wiederhergestellt werden:.
        /// </summary>
        internal static string messagebox_backup_restore_error_chars {
            get {
                return ResourceManager.GetString("messagebox_backup_restore_error_chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folgende Vokabelhefte konnten nicht wiederhergestellt werden:.
        /// </summary>
        internal static string messagebox_backup_restore_error_vhf {
            get {
                return ResourceManager.GetString("messagebox_backup_restore_error_vhf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ergebnis-Datei(en) konnte(n) nicht wiederhergestellt werden!.
        /// </summary>
        internal static string messagebox_backup_restore_error_vhr {
            get {
                return ResourceManager.GetString("messagebox_backup_restore_error_vhr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datensicherung wurde erfolgreich wiederhergestellt..
        /// </summary>
        internal static string messagebox_backup_restore_success {
            get {
                return ResourceManager.GetString("messagebox_backup_restore_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datensicherung wurde erfolgreich erstellt..
        /// </summary>
        internal static string messagebox_backup_success {
            get {
                return ResourceManager.GetString("messagebox_backup_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Vokabel konnte nicht geändert werden, da sie bereits vorhanden ist!.
        /// </summary>
        internal static string messagebox_cant_edit {
            get {
                return ResourceManager.GetString("messagebox_cant_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei ist fehlerhaft!.
        /// </summary>
        internal static string messagebox_faulty_file {
            get {
                return ResourceManager.GetString("messagebox_faulty_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Laden der Ergebnisse!.
        /// </summary>
        internal static string messagebox_fautly_results {
            get {
                return ResourceManager.GetString("messagebox_fautly_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei diesem Vokabelheft handelt es sich um eine Kopie, dessen Inhalt mit der Orginaldatei nicht identisch ist. Die Ergebnisse der Übungen werden bei dieser Datei gelöscht..
        /// </summary>
        internal static string messagebox_file_copy {
            get {
                return ResourceManager.GetString("messagebox_file_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei benötigt eine neuere Version von Vocup. Möchten Sie nach Updates suchen?.
        /// </summary>
        internal static string messagebox_new_program_version {
            get {
                return ResourceManager.GetString("messagebox_new_program_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei dieser Datei handelt es sich nicht um ein Vokabelheft!.
        /// </summary>
        internal static string messagebox_no_vhf {
            get {
                return ResourceManager.GetString("messagebox_no_vhf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Öffnen der Datei!.
        /// </summary>
        internal static string messagebox_reading_fault {
            get {
                return ResourceManager.GetString("messagebox_reading_fault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Vokabel ist bereits vorhanden!.
        /// </summary>
        internal static string messagebox_vocable_exists {
            get {
                return ResourceManager.GetString("messagebox_vocable_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herzlichen Glückwunsch! Sie haben bereits alle Vokabeln mehrmals hintereinander richtig übersetzt.
        ///	
        ///Tipp: Unter Optionen können Sie festlegen, wie oft eine Vokabel richtig hintereinander übersetzt werden muss, 
        ///damit sie als gelernt eingestuft wird.
        ///.
        /// </summary>
        internal static string no_vocables_to_learn {
            get {
                return ResourceManager.GetString("no_vocables_to_learn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie das Vokabelheft speichern bevor sie fortfahren? Alle nicht gespeicherten Daten gehen verloren..
        /// </summary>
        internal static string save_before_update {
            get {
                return ResourceManager.GetString("save_before_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das gewählte Vokabelheft existiert nicht mehr..
        /// </summary>
        internal static string treeview_doesnt_exists {
            get {
                return ResourceManager.GetString("treeview_doesnt_exists", resourceCulture);
            }
        }
    }
}
