//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vocup.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vocup.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Exportieren einer CSV Datei ist ein unerwarteter Fehler aufgetreten.
        ///Details:
        ///{0}.
        /// </summary>
        internal static string CsvExportError {
            get {
                return ResourceManager.GetString("CsvExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Importieren einer CSV Datei ist ein unerwarteter Fehler aufgetreten.
        ///Details:
        ///{0}.
        /// </summary>
        internal static string CsvImportError {
            get {
                return ResourceManager.GetString("CsvImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der CSV Header konnte nicht gelesen werden.
        ///Bitte stellen Sie sicher, dass die Datei nicht leer ist..
        /// </summary>
        internal static string CsvInvalidHeader {
            get {
                return ResourceManager.GetString("CsvInvalidHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der CSV Header verfügt über {0} Spalten, muss aber aus genau 2 Spalten bestehen.
        /// </summary>
        internal static string CsvInvalidHeaderColumns {
            get {
                return ResourceManager.GetString("CsvInvalidHeaderColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlerhafter CSV Header.
        /// </summary>
        internal static string CsvInvalidHeaderT {
            get {
                return ResourceManager.GetString("CsvInvalidHeaderT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie ein {0} - {1} Vokabelheft importieren, obwohl die Sprachen nicht übereinstimmen?.
        /// </summary>
        internal static string CsvInvalidLanguages {
            get {
                return ResourceManager.GetString("CsvInvalidLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unerwarteter Fehler.
        /// </summary>
        internal static string UnexpectedErrorT {
            get {
                return ResourceManager.GetString("UnexpectedErrorT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlerhafte Vokabelheft-Datei.
        /// </summary>
        internal static string VhfInvalidFileT {
            get {
                return ResourceManager.GetString("VhfInvalidFileT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Mutter- und Fremdsprache der Vokabelheft-Datei konnten nicht gelesen werden oder sind identisch.
        ///Stellen Sie sicher, dass die Datei nicht leer ist..
        /// </summary>
        internal static string VhfInvalidLanguages {
            get {
                return ResourceManager.GetString("VhfInvalidLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Version der Vokabelheft-Datei konnte nicht gelesen werden.
        ///Bitte stellen Sie sicher, dass die Datei nicht leer ist..
        /// </summary>
        internal static string VhfInvalidVersion {
            get {
                return ResourceManager.GetString("VhfInvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Vokabelheft-Datei enthält keinen gültigen Verweis auf ihre Ergebnisdatei.
        ///Stellen Sie sicher, dass die Datei nicht leer ist..
        /// </summary>
        internal static string VhfInvalidVhrCode {
            get {
                return ResourceManager.GetString("VhfInvalidVhrCode", resourceCulture);
            }
        }
    }
}
