//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vocup.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vocup.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben bereits alle Vokabeln mehrmals hintereinander richtig übersetzt.
        ///	
        ///Tipp: Unter Optionen können Sie festlegen, wie oft eine Vokabel richtig hintereinander übersetzt werden muss, damit sie als gelernt eingestuft wird..
        /// </summary>
        internal static string BookPracticeFinished {
            get {
                return ResourceManager.GetString("BookPracticeFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herzlichen Glückwunsch!.
        /// </summary>
        internal static string BookPracticeFinishedT {
            get {
                return ResourceManager.GetString("BookPracticeFinishedT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Exportieren einer CSV Datei ist ein unerwarteter Fehler aufgetreten.
        ///Details:
        ///{0}.
        /// </summary>
        internal static string CsvExportError {
            get {
                return ResourceManager.GetString("CsvExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Importieren einer CSV Datei ist ein unerwarteter Fehler aufgetreten.
        ///Details:
        ///{0}.
        /// </summary>
        internal static string CsvImportError {
            get {
                return ResourceManager.GetString("CsvImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der CSV Header konnte nicht gelesen werden.
        ///Bitte stellen Sie sicher, dass die Datei nicht leer ist..
        /// </summary>
        internal static string CsvInvalidHeader {
            get {
                return ResourceManager.GetString("CsvInvalidHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der CSV Header verfügt über {0} Spalten, muss aber aus genau 2 Spalten bestehen.
        /// </summary>
        internal static string CsvInvalidHeaderColumns {
            get {
                return ResourceManager.GetString("CsvInvalidHeaderColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlerhafter CSV Header.
        /// </summary>
        internal static string CsvInvalidHeaderT {
            get {
                return ResourceManager.GetString("CsvInvalidHeaderT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie ein {0} - {1} Vokabelheft importieren, obwohl die Sprachen nicht übereinstimmen?.
        /// </summary>
        internal static string CsvInvalidLanguages {
            get {
                return ResourceManager.GetString("CsvInvalidLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Vokabelheftdatei {0} existiert nicht mehr..
        /// </summary>
        internal static string OpenInExplorerNotFound {
            get {
                return ResourceManager.GetString("OpenInExplorerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei nicht gefunden.
        /// </summary>
        internal static string OpenInExplorerNotFoundT {
            get {
                return ResourceManager.GetString("OpenInExplorerNotFoundT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten die Änderungen am Vokabelheft speichern, bevor Sie es im Explorer öffnen? Sie können die Änderungen jederzeit auch später speichern..
        /// </summary>
        internal static string OpenInExplorerSave {
            get {
                return ResourceManager.GetString("OpenInExplorerSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jetzt speichern?.
        /// </summary>
        internal static string OpenInExplorerSaveT {
            get {
                return ResourceManager.GetString("OpenInExplorerSaveT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Sonderzeichendatei {0} konnte nicht geladen werden. Überprüfen Sie die Datei unter {1} und löschen sie diese gegebenenfalls..
        /// </summary>
        internal static string SpecialCharInvalidFile {
            get {
                return ResourceManager.GetString("SpecialCharInvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlerhafte Datei.
        /// </summary>
        internal static string SpecialCharInvalidFileT {
            get {
                return ResourceManager.GetString("SpecialCharInvalidFileT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unerwarteter Fehler.
        /// </summary>
        internal static string UnexpectedErrorT {
            get {
                return ResourceManager.GetString("UnexpectedErrorT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlerhafte Vokabelheft-Datei.
        /// </summary>
        internal static string VhfInvalidFileT {
            get {
                return ResourceManager.GetString("VhfInvalidFileT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Mutter- und Fremdsprache der Vokabelheft-Datei konnten nicht gelesen werden oder sind identisch.
        ///Stellen Sie sicher, dass die Datei nicht leer ist..
        /// </summary>
        internal static string VhfInvalidLanguages {
            get {
                return ResourceManager.GetString("VhfInvalidLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Eintrag dieser Vokabelheft-Datei ist ungültig. Die Datei kann deshalb nicht gelesen werden..
        /// </summary>
        internal static string VhfInvalidRow {
            get {
                return ResourceManager.GetString("VhfInvalidRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Version der Vokabelheft-Datei konnte nicht gelesen werden.
        ///Bitte stellen Sie sicher, dass die Datei nicht leer ist..
        /// </summary>
        internal static string VhfInvalidVersion {
            get {
                return ResourceManager.GetString("VhfInvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Vokabelheft-Datei enthält keinen gültigen Verweis auf ihre Ergebnisdatei.
        ///Stellen Sie sicher, dass die Datei nicht leer ist..
        /// </summary>
        internal static string VhfInvalidVhrCode {
            get {
                return ResourceManager.GetString("VhfInvalidVhrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Vokabelheft-Datei erfordert eine neuere Version von Vocup. Sie können entweder im Programm oder im Internet nach Updates suchen..
        /// </summary>
        internal static string VhfMustUpdate {
            get {
                return ResourceManager.GetString("VhfMustUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update erforderlich.
        /// </summary>
        internal static string VhfMustUpdateT {
            get {
                return ResourceManager.GetString("VhfMustUpdateT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Ergbnisdatei ist fehlerhaft und wird gelöscht. Die Übungsergebnisse gehen deshalb verloren..
        /// </summary>
        internal static string VhrInvalidFile {
            get {
                return ResourceManager.GetString("VhrInvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlerhafte Ergebnis-Datei.
        /// </summary>
        internal static string VhrInvalidFileT {
            get {
                return ResourceManager.GetString("VhrInvalidFileT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die referenzierte Ergebnisdatei passt nicht zu diesem Vokabelheft. Die Ergebnisse werden gelöscht..
        /// </summary>
        internal static string VhrInvalidRowCount {
            get {
                return ResourceManager.GetString("VhrInvalidRowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die referenzierte Ergebnisdatei wird von einem anderen Vokabelheft verwendet und passt nicht zu diesem. Daher werden keine Ergebnisse geladen..
        /// </summary>
        internal static string VhrInvalidRowCountAndOtherFile {
            get {
                return ResourceManager.GetString("VhrInvalidRowCountAndOtherFile", resourceCulture);
            }
        }
    }
}
