//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vocup.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Words {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Words() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vocup.Properties.Words", typeof(Words).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vokabelhefte hinzufügen.
        /// </summary>
        internal static string AddVocabularyBooks {
            get {
                return ResourceManager.GetString("AddVocabularyBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korrekt.
        /// </summary>
        internal static string Correct {
            get {
                return ResourceManager.GetString("Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Richtig wäre: {0}.
        /// </summary>
        internal static string CorrectWasX {
            get {
                return ResourceManager.GetString("CorrectWasX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Richtig wäre: {0} und {1}.
        /// </summary>
        internal static string CorrectWasXAndY {
            get {
                return ResourceManager.GetString("CorrectWasXAndY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Vokabelheft erstellen.
        /// </summary>
        internal static string CreateVocabularyBook {
            get {
                return ResourceManager.GetString("CreateVocabularyBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vokabelheft bearbeiten.
        /// </summary>
        internal static string EditVocabularyBook {
            get {
                return ResourceManager.GetString("EditVocabularyBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vokabel bearbeiten.
        /// </summary>
        internal static string EditWord {
            get {
                return ResourceManager.GetString("EditWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportieren.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertig.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fremdsprache.
        /// </summary>
        internal static string ForeignLanguage {
            get {
                return ResourceManager.GetString("ForeignLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importieren.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuletzt geübt.
        /// </summary>
        internal static string LastPracticed {
            get {
                return ResourceManager.GetString("LastPracticed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vokabelheft {0} - {1}.
        /// </summary>
        internal static string MailSubjectVocabularyBook {
            get {
                return ResourceManager.GetString("MailSubjectVocabularyBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muttersprache.
        /// </summary>
        internal static string MotherTongue {
            get {
                return ResourceManager.GetString("MotherTongue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datensicherung öffnen.
        /// </summary>
        internal static string OpenBackup {
            get {
                return ResourceManager.GetString("OpenBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vokabelheft öffnen.
        /// </summary>
        internal static string OpenVocabularyBook {
            get {
                return ResourceManager.GetString("OpenVocabularyBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insgesamt eine Vokabel.
        /// </summary>
        internal static string OverallOneWord {
            get {
                return ResourceManager.GetString("OverallOneWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insgesamt {0} Vokabeln.
        /// </summary>
        internal static string OverallXWords {
            get {
                return ResourceManager.GetString("OverallXWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teilweise korrekt.
        /// </summary>
        internal static string PartlyCorrect {
            get {
                return ResourceManager.GetString("PartlyCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datensicherung speichern.
        /// </summary>
        internal static string SaveBackup {
            get {
                return ResourceManager.GetString("SaveBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vokabelheft speichern.
        /// </summary>
        internal static string SaveVocabularyBook {
            get {
                return ResourceManager.GetString("SaveVocabularyBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seite.
        /// </summary>
        internal static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synonym.
        /// </summary>
        internal static string Synonym {
            get {
                return ResourceManager.GetString("Synonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übersetzen Sie von {0} nach {1}.
        /// </summary>
        internal static string TranslateFromTo {
            get {
                return ResourceManager.GetString("TranslateFromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vokabelhefte.
        /// </summary>
        internal static string VocabularyBooks {
            get {
                return ResourceManager.GetString("VocabularyBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocup.
        /// </summary>
        internal static string Vocup {
            get {
                return ResourceManager.GetString("Vocup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocup Backup-Datei.
        /// </summary>
        internal static string VocupBackupFile {
            get {
                return ResourceManager.GetString("VocupBackupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocup Übungsergebnis-Datei.
        /// </summary>
        internal static string VocupPracticeResultFile {
            get {
                return ResourceManager.GetString("VocupPracticeResultFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocup Vokabelheft-Datei.
        /// </summary>
        internal static string VocupVocabularyBookFile {
            get {
                return ResourceManager.GetString("VocupVocabularyBookFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falsch.
        /// </summary>
        internal static string Wrong {
            get {
                return ResourceManager.GetString("Wrong", resourceCulture);
            }
        }
    }
}
